server:
  port: 8092
spring:
  datasource:
    driver-class-name:  org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/fms_cloud_hl?useUnicode=true&characterEncoding=utf8
    username: root
    password: 178290
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl